version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # 아래 설정을 추가합니다
    target-branch: "develop"
    open-pull-requests-limit: 10
    vulnerability-threshold: "critical"