module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        basic: {
          0: 'var(--basic-0)',
          1: 'var(--basic-1)',
          2: 'var(--basic-2)',
          3: 'var(--basic-3)',
          4: 'var(--basic-4)',
          5: 'var(--basic-5)',
        },
        fg: {
          0: 'var(--fg-0)',
          1: 'var(--fg-1)',
          2: 'var(--fg-2)',
          3: 'var(--fg-3)',
          4: 'var(--fg-4)',
          5: 'var(--fg-5)',
          6: 'var(--fg-6)',
          7: 'var(--fg-7)',
        },
        point: {
          1: 'var(--point-1)',
          2: 'var(--point-2)',
          3: 'var(--point-3)',
          4: 'var(--point-4)',
          800: 'var(--point-800)',
          soft: 'var(--point-tint-soft)',
          fg: 'var(--accent-fg)',
        },
        success: {
          1: 'var(--success-1)',
          2: 'var(--success-2)',
          3: 'var(--success-3)',
          4: 'var(--success-4)',
        },
        info: {
          1: 'var(--info-1)',
          2: 'var(--info-2)',
          3: 'var(--info-3)',
          4: 'var(--info-4)',
        },
        warn: {
          1: 'var(--warn-1)',
          2: 'var(--warn-2)',
          3: 'var(--warn-3)',
          4: 'var(--warn-4)',
        },
        danger: {
          1: 'var(--danger-1)',
          2: 'var(--danger-2)',
          3: 'var(--danger-3)',
          4: 'var(--danger-4)',
        },
        neutral: {
          1: 'var(--neutral-1)',
          2: 'var(--neutral-2)',
          3: 'var(--neutral-3)',
          4: 'var(--neutral-4)',
        },
        accent2: {
          1: 'var(--accent2-1)',
          2: 'var(--accent2-2)',
          3: 'var(--accent2-3)',
          4: 'var(--accent2-4)',
        },
        accent3: {
          1: 'var(--accent3-1)',
          2: 'var(--accent3-2)',
          3: 'var(--accent3-3)',
          4: 'var(--accent3-4)',
        },
      },
    },
  },
  darkMode: 'media',
  plugins: [require('tailwindcss-safe-area'), require('@tailwindcss/typography')],
};
