/* tslint:disable */
/* eslint-disable */
/**
 * Presentation
 * 로그인 사용자가 okdohyuk 디자인 시스템 기반의 16:9 웹 프레젠테이션을 작성·저장하고, 발표 세션을 실행하며 같은 계정의 다른 기기에서 원격 제어하는 API다. document/theme는 서버가 허용된 typed JSON 구조와 크기를 검증하며 HTML 문자열을 실행하지 않는다.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 *
 * @export
 * @interface BaseException
 */
export interface BaseException {
    /**
     *
     * @type {string}
     * @memberof BaseException
     */
    'className'?: string;
    /**
     *
     * @type {string}
     * @memberof BaseException
     */
    'errorMessage'?: string;
    /**
     *
     * @type {number}
     * @memberof BaseException
     */
    'code'?: number;
    /**
     *
     * @type {string}
     * @memberof BaseException
     */
    'httpStatus'?: string;
    /**
     *
     * @type {string}
     * @memberof BaseException
     */
    'errorTrace'?: string;
}
/**
 * 로그인 사용자가 저장한 웹 프레젠테이션. document 는 임의 HTML이 아니라 허용된 layout/variant와 텍스트 블록으로 구성된 JSON 문서다.
 * @export
 * @interface Presentation
 */
export interface Presentation {
    /**
     * 프레젠테이션 DB PK
     * @type {number}
     * @memberof Presentation
     */
    'id': number;
    /**
     *
     * @type {string}
     * @memberof Presentation
     */
    'title': string;
    /**
     *
     * @type {string}
     * @memberof Presentation
     */
    'description'?: string | null;
    /**
     * 문서 JSON 스키마 버전
     * @type {number}
     * @memberof Presentation
     */
    'schemaVersion': number;
    /**
     * 낙관적 동시성 제어용 revision
     * @type {number}
     * @memberof Presentation
     */
    'revision': number;
    /**
     * 슬라이드 배열을 포함하는 typed presentation document
     * @type {{ [key: string]: any; }}
     * @memberof Presentation
     */
    'document': { [key: string]: any; };
    /**
     * okdohyuk 디자인 토큰 기반 테마 설정
     * @type {{ [key: string]: any; }}
     * @memberof Presentation
     */
    'theme': { [key: string]: any; };
    /**
     * 목표 발표 시간(초)
     * @type {number}
     * @memberof Presentation
     */
    'targetDurationSeconds': number;
    /**
     *
     * @type {string}
     * @memberof Presentation
     */
    'createdAt': string;
    /**
     *
     * @type {string}
     * @memberof Presentation
     */
    'updatedAt': string;
}
/**
 * 새 웹 프레젠테이션 생성 요청. document 는 서버가 구조와 크기를 검증한다.
 * @export
 * @interface PresentationCreateRequest
 */
export interface PresentationCreateRequest {
    /**
     *
     * @type {string}
     * @memberof PresentationCreateRequest
     */
    'title': string;
    /**
     *
     * @type {string}
     * @memberof PresentationCreateRequest
     */
    'description'?: string | null;
    /**
     *
     * @type {number}
     * @memberof PresentationCreateRequest
     */
    'schemaVersion'?: number;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof PresentationCreateRequest
     */
    'document': { [key: string]: any; };
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof PresentationCreateRequest
     */
    'theme': { [key: string]: any; };
    /**
     *
     * @type {number}
     * @memberof PresentationCreateRequest
     */
    'targetDurationSeconds'?: number;
}
/**
 * 로그인 사용자의 프레젠테이션 목록 페이지.
 * @export
 * @interface PresentationPage
 */
export interface PresentationPage {
    /**
     *
     * @type {number}
     * @memberof PresentationPage
     */
    'count': number;
    /**
     *
     * @type {Array<Presentation>}
     * @memberof PresentationPage
     */
    'results': Array<Presentation>;
}
/**
 * 발표 PC와 원격 리모컨이 공유하는 서버 권위 발표 세션 상태.
 * @export
 * @interface PresentationSession
 */
export interface PresentationSession {
    /**
     * 발표 세션 DB PK
     * @type {number}
     * @memberof PresentationSession
     */
    'id': number;
    /**
     *
     * @type {number}
     * @memberof PresentationSession
     */
    'presentationId': number;
    /**
     *
     * @type {string}
     * @memberof PresentationSession
     */
    'presentationTitle': string;
    /**
     *
     * @type {PresentationSessionStatus}
     * @memberof PresentationSession
     */
    'status': PresentationSessionStatus;
    /**
     *
     * @type {number}
     * @memberof PresentationSession
     */
    'currentSlideIndex': number;
    /**
     *
     * @type {number}
     * @memberof PresentationSession
     */
    'slideCount': number;
    /**
     *
     * @type {number}
     * @memberof PresentationSession
     */
    'documentRevision': number;
    /**
     *
     * @type {string}
     * @memberof PresentationSession
     */
    'startedAt': string;
    /**
     *
     * @type {string}
     * @memberof PresentationSession
     */
    'pausedAt'?: string | null;
    /**
     *
     * @type {string}
     * @memberof PresentationSession
     */
    'endedAt'?: string | null;
    /**
     *
     * @type {number}
     * @memberof PresentationSession
     */
    'elapsedSeconds': number;
    /**
     *
     * @type {number}
     * @memberof PresentationSession
     */
    'targetDurationSeconds': number;
    /**
     *
     * @type {string}
     * @memberof PresentationSession
     */
    'serverTime': string;
    /**
     *
     * @type {string}
     * @memberof PresentationSession
     */
    'updatedAt': string;
}


/**
 * 발표 세션에 보낼 원격 제어 명령.
 * @export
 * @enum {string}
 */

export const PresentationSessionCommand = {
    Next: 'NEXT',
    Previous: 'PREVIOUS',
    Goto: 'GOTO',
    PauseTimer: 'PAUSE_TIMER',
    ResumeTimer: 'RESUME_TIMER',
    End: 'END'
} as const;

export type PresentationSessionCommand = typeof PresentationSessionCommand[keyof typeof PresentationSessionCommand];


/**
 * 발표 세션 원격 제어 요청. GOTO 명령은 slideIndex 를 요구한다.
 * @export
 * @interface PresentationSessionCommandRequest
 */
export interface PresentationSessionCommandRequest {
    /**
     *
     * @type {PresentationSessionCommand}
     * @memberof PresentationSessionCommandRequest
     */
    'command': PresentationSessionCommand;
    /**
     *
     * @type {number}
     * @memberof PresentationSessionCommandRequest
     */
    'slideIndex'?: number | null;
}


/**
 * 발표 세션 상태.
 * @export
 * @enum {string}
 */

export const PresentationSessionStatus = {
    Running: 'RUNNING',
    Paused: 'PAUSED',
    Ended: 'ENDED'
} as const;

export type PresentationSessionStatus = typeof PresentationSessionStatus[keyof typeof PresentationSessionStatus];


/**
 * 프레젠테이션 수정 요청. revision 이 현재 서버 값과 다르면 409를 반환한다.
 * @export
 * @interface PresentationUpdateRequest
 */
export interface PresentationUpdateRequest {
    /**
     *
     * @type {string}
     * @memberof PresentationUpdateRequest
     */
    'title': string;
    /**
     *
     * @type {string}
     * @memberof PresentationUpdateRequest
     */
    'description'?: string | null;
    /**
     *
     * @type {number}
     * @memberof PresentationUpdateRequest
     */
    'schemaVersion': number;
    /**
     *
     * @type {number}
     * @memberof PresentationUpdateRequest
     */
    'revision': number;
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof PresentationUpdateRequest
     */
    'document': { [key: string]: any; };
    /**
     *
     * @type {{ [key: string]: any; }}
     * @memberof PresentationUpdateRequest
     */
    'theme': { [key: string]: any; };
    /**
     *
     * @type {number}
     * @memberof PresentationUpdateRequest
     */
    'targetDurationSeconds': number;
}

/**
 * PresentationApi - axios parameter creator
 * @export
 */
export const PresentationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @summary Delete Presentation
         * @param {number} id 프레젠테이션 DB PK
         * @param {string} authorization Bearer {token}
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePresentationId: async (id: number, authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletePresentationId', 'id', id)
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('deletePresentationId', 'authorization', authorization)
            const localVarPath = `/presentation/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }



            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get Presentation
         * @param {number} id 프레젠테이션 DB PK
         * @param {string} authorization Bearer {token}
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPresentationId: async (id: number, authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getPresentationId', 'id', id)
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('getPresentationId', 'authorization', authorization)
            const localVarPath = `/presentation/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }



            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 로그인 사용자의 프레젠테이션 목록을 최신 수정순으로 반환한다.
         * @summary Get My Presentations
         * @param {string} authorization Bearer {token}
         * @param {number} [page]
         * @param {number} [limit]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPresentationMe: async (authorization: string, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('getPresentationMe', 'authorization', authorization)
            const localVarPath = `/presentation/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }



            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get Active Presentation Session
         * @param {string} authorization Bearer {token}
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPresentationSessionsActive: async (authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('getPresentationSessionsActive', 'authorization', authorization)
            const localVarPath = `/presentation/sessions/active`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }



            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get Presentation Session
         * @param {number} sessionId 발표 세션 DB PK
         * @param {string} authorization Bearer {token}
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPresentationSessionsSessionId: async (sessionId: number, authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('getPresentationSessionsSessionId', 'sessionId', sessionId)
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('getPresentationSessionsSessionId', 'authorization', authorization)
            const localVarPath = `/presentation/sessions/{sessionId}`
                .replace(`{${"sessionId"}}`, encodeURIComponent(String(sessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }



            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 로그인 사용자의 새 프레젠테이션 생성.
         * @summary Create Presentation
         * @param {string} authorization Bearer {token}
         * @param {PresentationCreateRequest} presentationCreateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postPresentation: async (authorization: string, presentationCreateRequest: PresentationCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('postPresentation', 'authorization', authorization)
            // verify required parameter 'presentationCreateRequest' is not null or undefined
            assertParamExists('postPresentation', 'presentationCreateRequest', presentationCreateRequest)
            const localVarPath = `/presentation`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }



            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(presentationCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 기존 활성 세션을 종료하고 현재 문서 revision으로 새 발표 세션을 시작한다.
         * @summary Start Presentation Session
         * @param {number} id 발표할 프레젠테이션 DB PK
         * @param {string} authorization Bearer {token}
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postPresentationIdSessions: async (id: number, authorization: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('postPresentationIdSessions', 'id', id)
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('postPresentationIdSessions', 'authorization', authorization)
            const localVarPath = `/presentation/{id}/sessions`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }



            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Send Presentation Session Command
         * @param {number} sessionId 발표 세션 DB PK
         * @param {string} authorization Bearer {token}
         * @param {PresentationSessionCommandRequest} presentationSessionCommandRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postPresentationSessionsSessionIdCommands: async (sessionId: number, authorization: string, presentationSessionCommandRequest: PresentationSessionCommandRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionId' is not null or undefined
            assertParamExists('postPresentationSessionsSessionIdCommands', 'sessionId', sessionId)
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('postPresentationSessionsSessionIdCommands', 'authorization', authorization)
            // verify required parameter 'presentationSessionCommandRequest' is not null or undefined
            assertParamExists('postPresentationSessionsSessionIdCommands', 'presentationSessionCommandRequest', presentationSessionCommandRequest)
            const localVarPath = `/presentation/sessions/{sessionId}/commands`
                .replace(`{${"sessionId"}}`, encodeURIComponent(String(sessionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }



            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(presentationSessionCommandRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * revision이 현재 값과 다르면 409를 반환한다. 활성 발표 중에는 수정할 수 없다.
         * @summary Update Presentation
         * @param {number} id 프레젠테이션 DB PK
         * @param {string} authorization Bearer {token}
         * @param {PresentationUpdateRequest} presentationUpdateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putPresentationId: async (id: number, authorization: string, presentationUpdateRequest: PresentationUpdateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('putPresentationId', 'id', id)
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('putPresentationId', 'authorization', authorization)
            // verify required parameter 'presentationUpdateRequest' is not null or undefined
            assertParamExists('putPresentationId', 'presentationUpdateRequest', presentationUpdateRequest)
            const localVarPath = `/presentation/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }



            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(presentationUpdateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PresentationApi - functional programming interface
 * @export
 */
export const PresentationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PresentationApiAxiosParamCreator(configuration)
    return {
        /**
         *
         * @summary Delete Presentation
         * @param {number} id 프레젠테이션 DB PK
         * @param {string} authorization Bearer {token}
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePresentationId(id: number, authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePresentationId(id, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PresentationApi.deletePresentationId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Get Presentation
         * @param {number} id 프레젠테이션 DB PK
         * @param {string} authorization Bearer {token}
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPresentationId(id: number, authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Presentation>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPresentationId(id, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PresentationApi.getPresentationId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 로그인 사용자의 프레젠테이션 목록을 최신 수정순으로 반환한다.
         * @summary Get My Presentations
         * @param {string} authorization Bearer {token}
         * @param {number} [page]
         * @param {number} [limit]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPresentationMe(authorization: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PresentationPage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPresentationMe(authorization, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PresentationApi.getPresentationMe']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Get Active Presentation Session
         * @param {string} authorization Bearer {token}
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPresentationSessionsActive(authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PresentationSession>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPresentationSessionsActive(authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PresentationApi.getPresentationSessionsActive']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Get Presentation Session
         * @param {number} sessionId 발표 세션 DB PK
         * @param {string} authorization Bearer {token}
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPresentationSessionsSessionId(sessionId: number, authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PresentationSession>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPresentationSessionsSessionId(sessionId, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PresentationApi.getPresentationSessionsSessionId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 로그인 사용자의 새 프레젠테이션 생성.
         * @summary Create Presentation
         * @param {string} authorization Bearer {token}
         * @param {PresentationCreateRequest} presentationCreateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postPresentation(authorization: string, presentationCreateRequest: PresentationCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Presentation>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postPresentation(authorization, presentationCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PresentationApi.postPresentation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 기존 활성 세션을 종료하고 현재 문서 revision으로 새 발표 세션을 시작한다.
         * @summary Start Presentation Session
         * @param {number} id 발표할 프레젠테이션 DB PK
         * @param {string} authorization Bearer {token}
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postPresentationIdSessions(id: number, authorization: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PresentationSession>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postPresentationIdSessions(id, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PresentationApi.postPresentationIdSessions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Send Presentation Session Command
         * @param {number} sessionId 발표 세션 DB PK
         * @param {string} authorization Bearer {token}
         * @param {PresentationSessionCommandRequest} presentationSessionCommandRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postPresentationSessionsSessionIdCommands(sessionId: number, authorization: string, presentationSessionCommandRequest: PresentationSessionCommandRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PresentationSession>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postPresentationSessionsSessionIdCommands(sessionId, authorization, presentationSessionCommandRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PresentationApi.postPresentationSessionsSessionIdCommands']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * revision이 현재 값과 다르면 409를 반환한다. 활성 발표 중에는 수정할 수 없다.
         * @summary Update Presentation
         * @param {number} id 프레젠테이션 DB PK
         * @param {string} authorization Bearer {token}
         * @param {PresentationUpdateRequest} presentationUpdateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putPresentationId(id: number, authorization: string, presentationUpdateRequest: PresentationUpdateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Presentation>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.putPresentationId(id, authorization, presentationUpdateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PresentationApi.putPresentationId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PresentationApi - factory interface
 * @export
 */
export const PresentationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PresentationApiFp(configuration)
    return {
        /**
         *
         * @summary Delete Presentation
         * @param {number} id 프레젠테이션 DB PK
         * @param {string} authorization Bearer {token}
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePresentationId(id: number, authorization: string, options?: any): AxiosPromise<void> {
            return localVarFp.deletePresentationId(id, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get Presentation
         * @param {number} id 프레젠테이션 DB PK
         * @param {string} authorization Bearer {token}
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPresentationId(id: number, authorization: string, options?: any): AxiosPromise<Presentation> {
            return localVarFp.getPresentationId(id, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 로그인 사용자의 프레젠테이션 목록을 최신 수정순으로 반환한다.
         * @summary Get My Presentations
         * @param {string} authorization Bearer {token}
         * @param {number} [page]
         * @param {number} [limit]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPresentationMe(authorization: string, page?: number, limit?: number, options?: any): AxiosPromise<PresentationPage> {
            return localVarFp.getPresentationMe(authorization, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get Active Presentation Session
         * @param {string} authorization Bearer {token}
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPresentationSessionsActive(authorization: string, options?: any): AxiosPromise<PresentationSession> {
            return localVarFp.getPresentationSessionsActive(authorization, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get Presentation Session
         * @param {number} sessionId 발표 세션 DB PK
         * @param {string} authorization Bearer {token}
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPresentationSessionsSessionId(sessionId: number, authorization: string, options?: any): AxiosPromise<PresentationSession> {
            return localVarFp.getPresentationSessionsSessionId(sessionId, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 로그인 사용자의 새 프레젠테이션 생성.
         * @summary Create Presentation
         * @param {string} authorization Bearer {token}
         * @param {PresentationCreateRequest} presentationCreateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postPresentation(authorization: string, presentationCreateRequest: PresentationCreateRequest, options?: any): AxiosPromise<Presentation> {
            return localVarFp.postPresentation(authorization, presentationCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 기존 활성 세션을 종료하고 현재 문서 revision으로 새 발표 세션을 시작한다.
         * @summary Start Presentation Session
         * @param {number} id 발표할 프레젠테이션 DB PK
         * @param {string} authorization Bearer {token}
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postPresentationIdSessions(id: number, authorization: string, options?: any): AxiosPromise<PresentationSession> {
            return localVarFp.postPresentationIdSessions(id, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Send Presentation Session Command
         * @param {number} sessionId 발표 세션 DB PK
         * @param {string} authorization Bearer {token}
         * @param {PresentationSessionCommandRequest} presentationSessionCommandRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postPresentationSessionsSessionIdCommands(sessionId: number, authorization: string, presentationSessionCommandRequest: PresentationSessionCommandRequest, options?: any): AxiosPromise<PresentationSession> {
            return localVarFp.postPresentationSessionsSessionIdCommands(sessionId, authorization, presentationSessionCommandRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * revision이 현재 값과 다르면 409를 반환한다. 활성 발표 중에는 수정할 수 없다.
         * @summary Update Presentation
         * @param {number} id 프레젠테이션 DB PK
         * @param {string} authorization Bearer {token}
         * @param {PresentationUpdateRequest} presentationUpdateRequest
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putPresentationId(id: number, authorization: string, presentationUpdateRequest: PresentationUpdateRequest, options?: any): AxiosPromise<Presentation> {
            return localVarFp.putPresentationId(id, authorization, presentationUpdateRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PresentationApi - object-oriented interface
 * @export
 * @class PresentationApi
 * @extends {BaseAPI}
 */
export class PresentationApi extends BaseAPI {
    /**
     *
     * @summary Delete Presentation
     * @param {number} id 프레젠테이션 DB PK
     * @param {string} authorization Bearer {token}
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PresentationApi
     */
    public deletePresentationId(id: number, authorization: string, options?: RawAxiosRequestConfig) {
        return PresentationApiFp(this.configuration).deletePresentationId(id, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Get Presentation
     * @param {number} id 프레젠테이션 DB PK
     * @param {string} authorization Bearer {token}
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PresentationApi
     */
    public getPresentationId(id: number, authorization: string, options?: RawAxiosRequestConfig) {
        return PresentationApiFp(this.configuration).getPresentationId(id, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 로그인 사용자의 프레젠테이션 목록을 최신 수정순으로 반환한다.
     * @summary Get My Presentations
     * @param {string} authorization Bearer {token}
     * @param {number} [page]
     * @param {number} [limit]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PresentationApi
     */
    public getPresentationMe(authorization: string, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return PresentationApiFp(this.configuration).getPresentationMe(authorization, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Get Active Presentation Session
     * @param {string} authorization Bearer {token}
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PresentationApi
     */
    public getPresentationSessionsActive(authorization: string, options?: RawAxiosRequestConfig) {
        return PresentationApiFp(this.configuration).getPresentationSessionsActive(authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Get Presentation Session
     * @param {number} sessionId 발표 세션 DB PK
     * @param {string} authorization Bearer {token}
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PresentationApi
     */
    public getPresentationSessionsSessionId(sessionId: number, authorization: string, options?: RawAxiosRequestConfig) {
        return PresentationApiFp(this.configuration).getPresentationSessionsSessionId(sessionId, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 로그인 사용자의 새 프레젠테이션 생성.
     * @summary Create Presentation
     * @param {string} authorization Bearer {token}
     * @param {PresentationCreateRequest} presentationCreateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PresentationApi
     */
    public postPresentation(authorization: string, presentationCreateRequest: PresentationCreateRequest, options?: RawAxiosRequestConfig) {
        return PresentationApiFp(this.configuration).postPresentation(authorization, presentationCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 기존 활성 세션을 종료하고 현재 문서 revision으로 새 발표 세션을 시작한다.
     * @summary Start Presentation Session
     * @param {number} id 발표할 프레젠테이션 DB PK
     * @param {string} authorization Bearer {token}
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PresentationApi
     */
    public postPresentationIdSessions(id: number, authorization: string, options?: RawAxiosRequestConfig) {
        return PresentationApiFp(this.configuration).postPresentationIdSessions(id, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Send Presentation Session Command
     * @param {number} sessionId 발표 세션 DB PK
     * @param {string} authorization Bearer {token}
     * @param {PresentationSessionCommandRequest} presentationSessionCommandRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PresentationApi
     */
    public postPresentationSessionsSessionIdCommands(sessionId: number, authorization: string, presentationSessionCommandRequest: PresentationSessionCommandRequest, options?: RawAxiosRequestConfig) {
        return PresentationApiFp(this.configuration).postPresentationSessionsSessionIdCommands(sessionId, authorization, presentationSessionCommandRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * revision이 현재 값과 다르면 409를 반환한다. 활성 발표 중에는 수정할 수 없다.
     * @summary Update Presentation
     * @param {number} id 프레젠테이션 DB PK
     * @param {string} authorization Bearer {token}
     * @param {PresentationUpdateRequest} presentationUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PresentationApi
     */
    public putPresentationId(id: number, authorization: string, presentationUpdateRequest: PresentationUpdateRequest, options?: RawAxiosRequestConfig) {
        return PresentationApiFp(this.configuration).putPresentationId(id, authorization, presentationUpdateRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
