/* tslint:disable */
/* eslint-disable */
/**
 * Presentation
 * 로그인 사용자가 okdohyuk 디자인 시스템 기반의 16:9 웹 프레젠테이션을 작성·저장하고, 발표 세션을 실행하며 같은 계정의 다른 기기에서 원격 제어하는 API다. document/theme는 서버가 허용된 typed JSON 구조와 크기를 검증하며 HTML 문자열을 실행하지 않는다.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
